# Generated by Django 3.1.1 on 2020-09-18 19:44

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_auto_20200912_1357'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 9, 21, 19, 44, 53, 662822, tzinfo=utc), verbose_name='end date'),
        ),
    ]
